apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: php-apache-ingress
spec:
  rules:
  - host: dlp.srv.world # thay bằng domain hoặc IP bạn muốn
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: php-apache
            port:
              number: 80
