apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortio
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortio
  template:
    metadata:
      labels:
        app: fortio
    spec:
      containers:
      - name: fortio
        image: fortio/fortio:latest
        ports:
        - containerPort: 8080   # HTTP Web UI
        - containerPort: 8079   # gRPC load
